### ISSUE TITLE
[[object Object]]Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by tiansin** [mattogodoy/hacker-sounds#1]
https://github.com/mattogodoy/hacker-sounds/blob/de7ca83c5bf3310c06b5fa72164a5b0c1becfad5/src/extension.ts#L78

**Comment by mattogodoy** [comment]
Fixed in commit [1b1b803](https://github.com/mattogodoy/hacker-sounds/commit/1b1b803ca8213a71296baaefe84f6b19cb0258e1)

Thanks for reporting the issue!

**Comment by tiansin** [comment]
@mattogodoy This issue has not been fixed.
`TypeError: Cannot read property 'text' of undefined extension.js:75`

**Comment by mattogodoy** [comment]
Did you update the extension to 1.0.3? If so, could you please tell me:
- the steps you follow to reproduce the error
- the operative system you are running
- where do you see that error

Thanks!

**Comment by tiansin** [comment]
version:1.03
system: macos 10.13.6
@mattogodoy After I was coding normally for a while, open the developer tools to see this error log

**Comment by mattogodoy** [comment]
I've been trying to reproduce it, but I'm not able to do it.
I'll keep looking. Thanks for the data!

**Comment by tiansin** [comment]
@mattogodoy 
![Screen Shot 2019-12-15 at 02 42 47](https://user-images.githubusercontent.com/4232281/70853116-aa7e4480-1ee4-11ea-8af3-639e4da3bd6e.png)
