### ISSUE TITLE
Can we feel like hackers in the terminal?

### ISSUE THREAD

**Issue by AlexKinney** [mattogodoy/hacker-sounds#13]
I know the terminal already means I'm hacking but having these sounds while typing in it would really help boost my self-esteem further (this app has already done wonders for me ;)). 

Separately, thanks for making this extension, everything about this is fantastic and it continues to make me chuckle.

**Comment by mattogodoy** [comment]
Thanks for your kind words!

Having this in the terminal would be awesome indeed. Do you mean the one that is embedded in VSCode or a regular terminal?
I personally use iTerm2 with zsh, so I guess it should be possible to write a plugin for one of those, but I guess it's a completely different project and maybe in another programming language too.

I'll take a look around and see if it's possible. If you have any suggestion just let me know :)

**Comment by xirokif** [comment]
> Thanks for your kind words!
> 
> Having this in the terminal would be awesome indeed. Do you mean the one that is embedded in VSCode or a regular terminal?
> I personally use iTerm2 with zsh, so I guess it should be possible to write a plugin for one of those, but I guess it's a completely different project and maybe in another programming language too.
> 
> I'll take a look around and see if it's possible. If you have any suggestion just let me know :)

I think he means the embedded one.

**Comment by mattogodoy** [comment]
In both cases the embedded terminal is the same one, with the difference that the embedded one opens it inside VSCode. You can even change which terminal to use.
My guess is that VSCode extensions have no control over that, but I'd have to investigate further.
If you guys find any related information please let me know!
