### ISSUE TITLE
Will you ever release this on Intellij Idea?

### ISSUE THREAD

**Issue by HydraSyntax** [mattogodoy/hacker-sounds#15]
This plugin is amazing, but I am switching over to IntelliJ Idea soon. Do you know any way to carry this plugin over to IntelliJ?

**Comment by mattogodoy** [comment]
Thanks a lot!
I have no plans to port this extension outside VSCode because it's what I use every day.
Of course you are more than allowed to take the sounds and any piece of logic you might need from this project and write an IntelliJ extension yourself 😃
