### ISSUE TITLE
Forgot publish?

### ISSUE THREAD

**Issue by liangzr** [mattogodoy/hacker-sounds#6]
Hey, @mattogodoy . Did you forget to publish the new version on vscode extension marketplace?

**Comment by mattogodoy** [comment]
Hello!
Nope, I did not forget. I was making some modifications so it works in all platforms.
I'll finish and publish the new version today :)

**Comment by liangzr** [comment]
Gotcha! I saw that README is updated, thought that you forgot to update the extension. Thanks for your works ❤️, I will close this issue!

**Comment by mattogodoy** [comment]
Done! It's published now :)

https://marketplace.visualstudio.com/items?itemName=mattogodoy.hacker-sounds
