### ISSUE TITLE
Custom music pack

### ISSUE THREAD

**Issue by liangzr** [mattogodoy/hacker-sounds#8]
Recently Apple Music always pushes me Bach's songs, this inspired me that maybe I can knock the keyboard like a piano! But the idea needs the support of custom music pack, maybe it makes coding more elegant after updating the music pack 😀

**Comment by mattogodoy** [comment]
Sounds good! But I would do it in a different project since the name "Hacker Sounds" would no longe apply.
Yo could forge this project and add that functionality if you want :D

**Comment by reubenremy** [comment]
Could the sound used for "Tab" be also used for parentheses, curly braces & brackets? or something similar?

**Comment by mattogodoy** [comment]
It's a good idea! I'm quite busy right now, but if you want to make a PR with those changes I'll take a look at it :)
